export const s = {
  page: {
    minHeight: "100vh",
    background: "#fff9f0",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    fontFamily: "'Vazirmatn', 'Tahoma', sans-serif",
    color: "#280000",
    padding: "0 1rem 3rem",
    paddingBottom: "1.5rem",
    direction: "rtl" as const,
    textAlign: "right" as const,
  },
  topBar: {
    width: "100%",
    maxWidth: 480,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1.25rem 0 0.5rem",
    borderBottom: "1px solid #e0cdaf",
    marginBottom: "2.5rem",
  },
  brand: {
    fontSize: "0.9rem",
    fontWeight: 500,
    color: "#280000",
    display: "flex",
    alignItems: "center",
    gap: "0.4rem",
  },
  brandDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#9f3422",
    display: "inline-block",
    flexShrink: 0,
  },
  aboutBtn: {
    background: "transparent",
    border: "1.5px solid #280000",
    color: "#280000",
    fontFamily: "'Vazirmatn', 'Tahoma', sans-serif",
    fontSize: "0.7rem",
    padding: "0.35rem 0.8rem",
    cursor: "pointer",
    borderRadius: 8,
  },
  logoWrap: { textAlign: "center" as const, marginBottom: "2rem" },
  logoText: {
    fontSize: "clamp(1.2rem,5vw,1.6rem)",
    fontWeight: 500,
    color: "#280000",
  },
  logoSub: { fontSize: "0.63rem", color: "#9f3422", marginTop: "0.3rem" },
  locationBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.3rem",
    marginTop: "0.55rem",
    border: "1px solid #e0cdaf",
    padding: "0.2rem 0.65rem",
    fontSize: "0.62rem",
    color: "#73a89c",
  },
  priceBadge: {
    display: "inline-flex",
    alignItems: "center",
    marginTop: "0.4rem",
    background: "#9f3422",
    padding: "0.25rem 0.8rem",
    fontSize: "0.65rem",
    color: "#fff9f0",
    fontWeight: 500,
  },
  dividerLine: {
    width: 32,
    height: 1,
    background: "#e0cdaf",
    margin: "0.9rem auto 0",
  },

  form: {
    width: "100%",
    maxWidth: 480,
    display: "flex",
    flexDirection: "column" as const,
    gap: "1.5rem",
  },
  sectionLabel: {
    fontSize: "0.58rem",
    color: "#cc8831",
    borderBottom: "1px solid #f6e4cb",
    paddingBottom: "0.35rem",
    marginBottom: "-0.5rem",
  },
  fieldWrap: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.4rem",
  },
  label: { fontSize: "0.68rem", color: "#511e1d", fontWeight: 500 },
  input: {
    background: "transparent",
    border: "none",
    borderBottom: "1.5px solid #e0cdaf",
    borderRadius: 8,
    fontFamily: "'Vazirmatn', 'Tahoma', sans-serif",
    fontSize: "0.85rem",
    color: "#280000",
    padding: "0.5rem 0",
    outline: "none",
    width: "100%",
    direction: "rtl" as const,
    textAlign: "right" as const,
    transition: "border-color 0.18s",
  },
  datePickerWrapper: {
    position: "relative" as const,
  },
  toastContainer: {
    position: "fixed" as const,
    top: 16,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 60,
    width: "min(100%, 480px)",
    padding: "0 1rem",
    pointerEvents: "none" as const,
  },
  toastMessage: {
    background: "#280000",
    color: "#fff9f0",
    borderRadius: 8,
    padding: "0.9rem 1rem",
    boxShadow: "0 14px 32px rgba(40, 0, 0, 0.14)",
    fontSize: "0.85rem",
    textAlign: "center" as const,
    pointerEvents: "auto" as const,
  },
  calendarPopup: {
    position: "absolute" as const,
    top: "calc(100% + 0.5rem)",
    left: 0,
    zIndex: 30,
    minWidth: 280,
    maxWidth: "100%",
    border: "1.5px solid #e0cdaf",
    borderRadius:8,
    background: "#fff9f0",
    boxShadow: "0 18px 45px rgba(40, 0, 0, 0.08)",
  },

  /* ── کارت پرداخت ── */
  payCard: {
    border: "1.5px solid #e0cdaf",
    padding: "1.1rem 1.2rem",
    background: "#fdf6ec",
    borderRadius: 8,
    boxShadow: "8px 8px 0px rgb(224,205,175)",
  },
  payRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "0.9rem",
  },
  payAmount: {
    fontSize: "1.4rem",
    fontWeight: 500,
    color: "#9f3422",
    lineHeight: 1,
  },
  payAmountSub: { fontSize: "0.58rem", color: "#cc8831", marginTop: "0.2rem" },
  payCardLabel: {
    fontSize: "0.6rem",
    color: "#511e1d",
    marginBottom: "0.3rem",
  },
  payCardNumber: {
    fontFamily: "'Courier New', monospace",
    fontSize: "1.05rem",
    letterSpacing: "0.1em",
    color: "#280000",
    fontWeight: 600,
    direction: "ltr" as const,
    display: "block",
    marginBottom: "0.6rem",
  },
  copyBtn: {
    background: "transparent",
    border: "1px solid #e0cdaf",
    color: "#511e1d",
    fontFamily: "'Vazirmatn', 'Tahoma', sans-serif",
    fontSize: "0.62rem",
    padding: "0.25rem 0.7rem",
    cursor: "pointer",
    borderRadius: 8,
    transition: "all 0.15s",
  },
  payNote: {
    fontSize: "0.62rem",
    color: "#73a89c",
    marginTop: "0.75rem",
    lineHeight: 1.9,
    borderTop: "1px dashed #e0cdaf",
    paddingTop: "0.6rem",
  },

  /* ── آپلود ── */
  uploadZone: {
    border: "1.5px dashed #e0cdaf",
    padding: "1.4rem 1rem",
    textAlign: "center" as const,
    cursor: "pointer",
    transition: "border-color 0.18s, background 0.18s",
    borderRadius: 8,
    boxShadow: "8px 8px 0px rgb(224,205,175)",
  },
  uploadZoneActive: { borderColor: "#73a89c", background: "#f0f7f6" },
  uploadText: { fontSize: "0.72rem", color: "#511e1d", lineHeight: 1.9 },
  uploadSub: { fontSize: "0.6rem", color: "#cc8831", marginTop: "0.2rem" },
  uploadPreview: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    padding: "0.55rem 0.8rem",
    border: "1px solid #73a89c",
    background: "#f0f7f6",
    marginTop: "0.5rem",
    fontSize: "0.7rem",
    color: "#280000",
    borderRadius: 8,
    boxShadow: "8px 8px 0px rgb(224,205,175)",
  },
  removeBtn: {
    marginRight: "auto",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#9f3422",
    fontSize: "0.9rem",
    lineHeight: 1,
    padding: 0,
  },

  footerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: "1.2rem",
    borderTop: "1px solid #e0cdaf",
  },
  hint: { fontSize: "0.62rem", color: "#cc8831" },
  submitBtn: {
    background: "#9f3422",
    border: "1.5px solid #9f3422",
    color: "#fff9f0",
    fontFamily: "'Vazirmatn', 'Tahoma', sans-serif",
    fontSize: "0.72rem",
    padding: "0.7rem 1.6rem",
    cursor: "pointer",
    transition: "background 0.18s",
    borderRadius: 0,
  },

  /* ── موفقیت ── */
  success: {
    textAlign: "center" as const,
    padding: "3rem 1rem",
    maxWidth: 480,
    width: "100%",
  },
  successEnter: {
    opacity: 0,
    transform: "translateY(16px) scale(0.98)",
    transition: "opacity 220ms ease, transform 220ms ease",
  },
  successActive: {
    opacity: 1,
    transform: "translateY(0) scale(1)",
    transition: "opacity 220ms ease, transform 220ms ease",
  },
  formEnter: {
    opacity: 0,
    transform: "translateY(16px) scale(0.98)",
    transition: "opacity 220ms ease, transform 220ms ease",
  },
  formActive: {
    opacity: 1,
    transform: "translateY(0) scale(1)",
    transition: "opacity 220ms ease, transform 220ms ease",
  },
  successIcon: { fontSize: "2rem", marginBottom: "1rem" },
  successTitle: {
    fontSize: "1.2rem",
    fontWeight: 500,
    color: "#280000",
    marginBottom: "0.8rem",
  },
  successCard: {
    border: "1px solid #e0cdaf",
    padding: "0.9rem 1.1rem",
    marginBottom: "1rem",
    textAlign: "right" as const,
    borderRadius: 8,
    boxShadow: "8px 8px 0px rgb(224,205,175)",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "0.72rem",
    color: "#511e1d",
    lineHeight: 2.4,
    borderBottom: "1px dashed #f6e4cb",
  },
  rowLast: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "0.72rem",
    color: "#511e1d",
    lineHeight: 2.4,
  },
  rowKey: { color: "#9f3422", fontSize: "0.62rem", fontWeight: 500 },
  successNote: { fontSize: "0.7rem", color: "#511e1d", lineHeight: 2 },
  resetBtn: {
    marginTop: "1.4rem",
    background: "transparent",
    border: "1.5px solid #280000",
    color: "#280000",
    fontFamily: "'Vazirmatn', 'Tahoma', sans-serif",
    fontSize: "0.7rem",
    padding: "0.55rem 1.2rem",
    cursor: "pointer",
    borderRadius: 0,
  },

  /* ── دیالوگ ── */
  dlg: {
    background: "#fff9f0",
    border: "1.5px solid #e0cdaf",
    borderRadius: 8,
    boxShadow: "8px 8px 0px rgb(224,205,175)",
    maxWidth: 400,
    width: "calc(100vw - 2rem)",
    padding: "2rem 1.5rem",
    fontFamily: "'Vazirmatn', 'Tahoma', sans-serif",
    direction: "rtl" as const,
    textAlign: "right" as const,
  },
  dlgTitle: {
    fontSize: "1.05rem",
    fontWeight: 500,
    color: "#280000",
    textAlign: "right" as const,
    marginBottom: "0.3rem",
  },
  dlgSub: { fontSize: "0.62rem", color: "#9f3422", marginBottom: "1rem" },
  dlgBody: {
    fontSize: "0.78rem",
    lineHeight: 2.1,
    color: "#511e1d",
    marginBottom: "1rem",
  },
  dlgAccent: {
    borderRight: "2px solid #73a89c",
    paddingRight: "0.8rem",
    fontSize: "0.73rem",
    lineHeight: 2,
    color: "#280000",
    marginBottom: "1.2rem",
  },
  dlgGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.6rem" },
  dlgBox: {
    border: "1px solid #e0cdaf",
    padding: "0.6rem 0.75rem",
    fontSize: "0.65rem",
    lineHeight: 1.9,
    color: "#511e1d",
  },
  dlgBoxLabel: {
    color: "#9f3422",
    fontSize: "0.58rem",
    fontWeight: 500,
    display: "block" as const,
  },
}
